# Generated by Django 5.1.6 on 2025-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_package_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_status',
            new_name='package_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-23 00:00:00'),
            preserve_default=False,
        ),
    ]
