# Generated by Django 5.1.6 on 2025-02-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_payment_status_booking_package_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='package_status',
            new_name='payment_status',
        ),
    ]
